# Generated by Django 3.1.7 on 2021-03-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('spicies', models.CharField(max_length=3)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=4)),
            ],
        ),
    ]
