# Generated by Django 3.1.7 on 2021-03-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catdog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalimage',
            old_name='spicies',
            new_name='species',
        ),
    ]
